
CREATE TABLE PUBLIC.ITEM (
    ID INTEGER IDENTITY NOT NULL,
    DESCRIPTION VARCHAR,
    NAME VARCHAR,
    PRICE DOUBLE,
    VERSION INTEGER,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.CART (
    ID INTEGER IDENTITY NOT NULL,
    VERSION INTEGER,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    CUSTOMER_ID INTEGER,
    PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.CART_ITEM (
    ID INTEGER IDENTITY NOT NULL,
    QUANTITY INTEGER,
    VERSION INTEGER,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    CART_ID INTEGER,
    ITEM_ID INTEGER,
    PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.CUSTOMER (
    ID INTEGER IDENTITY NOT NULL,
    EMAIL VARCHAR,
    FIRSTNAME VARCHAR,
    LASTNAME VARCHAR,
    VERSION INTEGER,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.PLATFORM_ROLE (
    ID INTEGER IDENTITY NOT NULL,
    ROLENAME VARCHAR,
    VERSION INTEGER,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.PLATFORM_USER (
    ID INTEGER IDENTITY NOT NULL,
    PWHASH VARCHAR,
    USERNAME VARCHAR,
    VERSION INTEGER,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,
    CUSTOMER_ID INTEGER UNIQUE,
    PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.PLATFORM_USER_ROLE (
    ROLE_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    PRIMARY KEY (ROLE_ID,USER_ID)
);

ALTER TABLE PUBLIC.CART ADD CONSTRAINT FK_CART_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES PUBLIC.CUSTOMER(ID);

ALTER TABLE PUBLIC.CART_ITEM ADD CONSTRAINT FK_CART_ITEM_CART_ID FOREIGN KEY (CART_ID) REFERENCES PUBLIC.CART(ID);
ALTER TABLE PUBLIC.CART_ITEM ADD CONSTRAINT FK_CART_ITEM_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES PUBLIC.ITEM(ID);

ALTER TABLE PUBLIC.PLATFORM_USER ADD CONSTRAINT FK_PLATFORM_USER_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES PUBLIC.CUSTOMER(ID);
ALTER TABLE PUBLIC.PLATFORM_USER_ROLE ADD CONSTRAINT FK_PLATFORM_USER_ROLE_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES PUBLIC.PLATFORM_ROLE(ID);
ALTER TABLE PUBLIC.PLATFORM_USER_ROLE ADD CONSTRAINT FK_PLATFORM_USER_ROLE_USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC.PLATFORM_USER(ID);


